### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by juliapottkaemper** [ilikerobots/ascii2edf#1]
Hello,

I do not know if this account is still active as this program was posted 8 years ago, but I was wondering if you would be able to help me use this program. I am desperately looking for an automated conversion from ascii to edf file format and this seems to be the right program to do so. I have, however, no experience with C++ yet. From what I have read so far, I need to incorporate an xml file that the program uses, but I do not quite understand how to prepare it? Is it also possible to give the channels names that need to be changed? 
Thanks already in advance.

Best,
Julia

**Comment by ilikerobots** [comment]
@juliapottkaemper , it's been a long time, I didn't use this very  much, and I no longer have any of the project files from when I was working on it, so at this point I'm pretty much reading with as fresh eyes as you have. :/ 

This program was based on [EDF browser](https://gitlab.com/Teuniz/EDFbrowser/), which includes an [ascii2edf conversion](https://gitlab.com/Teuniz/EDFbrowser/-/blob/master/cnvs/ascii2edf.cpp).  The purpose for my script above was just to reproduce EDFBrowser's ascii -> edf conversion from the command line, for use in batch processing.  The XML file for configuration however, is (or was) the one produced by EDFBrowser.   

If you can get EDFBrowser up and running, you may be able to see how the xml files are formatted (beyond the one in the example here) use them with this script.

**Comment by juliapottkaemper** [comment]
Hi @ilikerobots 
Thanks so much for your reply :) I will try that!
